app = "clinicflow-web-mbardhi"
primary_region = "ams"

[build]
  [build.args]
    API_INTERNAL_URL = "http://clinicflow-api-mbardhi.internal:8080"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
